version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./vol:/var/lib/postgresql/data